linters:
  rubocop:
    display_cop_names: true
files:
  ignore:
    - "bin/*"
    - "db/*"
    - "config/*"
    - "Guardfile"
    - "Rakefile"
    - 'normalize.css'
    - 'reboot.css'
    - 'reset.css'
    - './spec/*'
fixers:
  enable: true